import { type ElementType } from 'react';
import {
  Type,
  ImageIcon,
  Calculator,
  ArrowLeftRight,
  Binary,
  Globe,
  Code,
  Package,
} from 'lucide-react';

export interface DirectoryToolItem {
  id: string;
  title: string;
  description: string;
  path: string;
  implemented: boolean;
}

export interface ToolCategoryGroup {
  id: string;
  title: string;
  description: string;
  icon: ElementType;
  color: string;
  gradient: string;
  tools: DirectoryToolItem[];
}

export const toolCategories: ToolCategoryGroup[] = [
  {
    id: 'text',
    title: 'Text Tools',
    description: 'Analyze, format and manipulate text with ease',
    icon: Type,
    color: 'textTool',
    gradient: 'textTool-gradient',
    tools: [
      { id: 'word-counter', title: 'Word Counter', description: 'Count characters, words, sentences and paragraphs', path: '/tools/text/word-counter', implemented: true },
      { id: 'text-case-converter', title: 'Text Case Converter', description: 'Convert text between cases (upper, lower, title, etc.)', path: '/tools/text/text-case-converter', implemented: true },
      { id: 'text-to-slug', title: 'Text to Slug', description: 'Convert text to URL-friendly slugs', path: '/tools/text/text-to-slug', implemented: true },
      { id: 'lorem-ipsum-generator', title: 'Lorem Ipsum Generator', description: 'Generate placeholder text for designs', path: '/tools/text/lorem-ipsum-generator', implemented: true },
      { id: 'remove-line-breaks', title: 'Remove Line Breaks', description: 'Remove or add line breaks in text', path: '/tools/text/remove-line-breaks', implemented: true },
      { id: 'random-word-generator', title: 'Random Word Generator', description: 'Generate random words for creative writing', path: '/tools/text/random-word-generator', implemented: true },
      { id: 'terms-and-condition-generator', title: 'Terms and Condition Generator', description: 'Generate website terms and conditions text', path: '/tools/text/terms-and-condition-generator', implemented: true },
      { id: 'disclaimer-generator', title: 'Disclaimer Generator', description: 'Generate disclaimers for your website or app', path: '/tools/text/disclaimer-generator', implemented: true },
      { id: 'text-repeater', title: 'Text Repeater', description: 'Repeat text a specified number of times', path: '/tools/text/text-repeater', implemented: true },
      { id: 'text-sorter', title: 'Text Sorter', description: 'Sort lines of text alphabetically or numerically', path: '/tools/text/sorter', implemented: true },
      { id: 'comma-separator', title: 'Comma Separator', description: 'Separate text with commas', path: '/tools/text/comma-separator', implemented: true },
    ],
  },
  {
    id: 'image',
    title: 'Image Tools',
    description: 'Resize, convert and optimize your images',
    icon: ImageIcon,
    color: 'imageTool',
    gradient: 'imageTool-gradient',
    tools: [
      { id: 'image-resizer', title: 'Image Resizer', description: 'Resize and compress images with preview', path: '/tools/image/image-resizer', implemented: true },
      { id: 'image-to-base64', title: 'Image to Base64', description: 'Convert images to base64 encoded strings', path: '/tools/image/image-to-base64', implemented: true },
      { id: 'base64-to-image', title: 'Base64 to Image', description: 'Convert base64 strings back to images', path: '/tools/image/base64-to-image', implemented: true },
      { id: 'image converter', title: 'Image Converter', description: 'Convert images between different formats', path: '/tools/image/ImageConverter', implemented: true },
      { id: 'image cropper', title: 'Image Cropper', description: 'Crop images to desired dimensions', path: '/tools/image/ImageCropper', implemented: true },
      { id: 'image enlarger', title: 'Image Enlarger', description: 'Enlarge images without losing quality', path: '/tools/image/ImageEnlarger', implemented: true },
      { id: 'flip image', title: 'Flip Image', description: 'Flip images horizontally or vertically', path: '/tools/image/FlipImage', implemented: true },
      { id: 'Jpg Converter', title: 'JPG Converter', description: 'Convert images to JPG format', path: '/tools/image/JPGConverter', implemented: true },
      { id: 'Jpg to bmp', title: 'JPG to BMP', description: 'Convert JPG images to BMP format', path: '/tools/image/JPGtoBMP', implemented: true },
      { id: 'Jpg to gif', title: 'JPG to GIF', description: 'Convert JPG images to GIF format', path: '/tools/image/JPGtoGIF', implemented: true },
      { id: 'Jpg to ico', title: 'JPG to ico', description: 'Convert JPG images to ICO format', path: '/tools/image/JPGtoICO', implemented: true },
      { id: 'Jpg to png', title: 'JPG to PNG', description: 'Convert JPG images to PNG format', path: '/tools/image/JPGtoPNG', implemented: true },
      { id: 'Jpg to webp', title: 'JPG to WEBP', description: 'Convert JPG images to WebP format', path: '/tools/image/JPGtoWebP', implemented: true },
      { id: 'png to bmp', title: 'PNG to BMP', description: 'Convert PNG images to BMP format', path: '/tools/image/PNGtoBMP', implemented: true },
      { id: 'png to gif', title: 'PNG to GIF', description: 'Convert PNG images to GIF format', path: '/tools/image/PNGtoGIF', implemented: true },
      { id: 'png to ico', title: 'PNG to ICO', description: 'Convert PNG images to ICO format', path: '/tools/image/PNGtoICO', implemented: true },
      { id: 'png to jpg', title: 'PNG to JPG', description: 'Convert PNG images to JPG format', path: '/tools/image/PNGtoJPG', implemented: true },
      { id: 'rotate image', title: 'Rotate Image', description: 'Rotate images by specified angles', path: '/tools/image/RotateImage', implemented: true },
      { id: 'webp to jpg', title: 'WEBP to JPG', description: 'Convert WEBP images to JPG format', path: '/tools/image/WebPtoJPG', implemented: true },
      { id: 'webp to png', title: 'WEBP to PNG', description: 'Convert WEBP images to PNG format', path: '/tools/image/WebPtoPNG', implemented: true },
    ],
  },
  {
    id: 'calculators',
    title: 'Calculators',
    description: 'Handy calculators for various needs',
    icon: Calculator,
    color: 'calculatorTool',
    gradient: 'calculatorTool-gradient',
    tools: [
      { id: 'age-calculator', title: 'Age Calculator', description: 'Calculate age based on birth date', path: '/tools/calculators/age-calculator', implemented: true },
      { id: 'percentage-calculator', title: 'Percentage Calculator', description: 'Calculate percentages easily', path: '/tools/calculators/percentage-calculator', implemented: true },
      { id: 'average-calculator', title: 'Average Calculator', description: 'Calculate mean, median, mode and other statistics', path: '/tools/calculators/average-calculator', implemented: true },
      { id: 'confidence-interval-calculator', title: 'Confidence Interval Calculator', description: 'Calculate statistical confidence intervals', path: '/tools/calculators/confidence-interval-calculator', implemented: true },
      { id: 'margin-calculator', title: 'Margin Calculator', description: 'Calculate profit margins and markups', path: '/tools/calculators/margin-calculator', implemented: true },
      { id: 'probability-calculator', title: 'Probability Calculator', description: 'Calculate probability of various events', path: '/tools/calculators/probability-calculator', implemented: true },
      { id: 'paypal-fee-calculator', title: 'PayPal Fee Calculator', description: 'Calculate PayPal transaction fees', path: '/tools/calculators/paypal-fee-calculator', implemented: true },
      { id: 'cpm-calculator', title: 'CPM Calculator', description: 'Calculate cost per thousand impressions for advertising', path: '/tools/calculators/cpm-calculator', implemented: true },
      { id: 'loan-calculator', title: 'Loan Calculator', description: 'Calculate loan payments, interest, and amortization', path: '/tools/calculators/loan-calculator', implemented: true },
      { id: 'gst-calculator', title: 'GST Calculator', description: 'Calculate Goods and Services Tax', path: '/tools/calculators/gst-calculator', implemented: true },
      { id: 'days-calculator', title: 'Days Calculator', description: 'Calculate days between dates', path: '/tools/calculators/days-calculator', implemented: true },
      { id: 'hours-calculator', title: 'Hours Calculator', description: 'Calculate hours worked and time differences', path: '/tools/calculators/hours-calculator', implemented: true },
      { id: 'month-calculator', title: 'Month Calculator', description: 'Calculate months between dates', path: '/tools/calculators/month-calculator', implemented: true },
      { id: 'stripe-fee-calculator', title: 'Stripe Fee Calculator', description: 'Calculate Stripe payment processing fees', path: '/tools/calculators/stripe-fee-calculator', implemented: true },
      { id: 'calorie-calculator', title: 'Calorie Calculator', description: 'Calculate daily calorie needs based on various factors', path: '/tools/calculators/calorie-calculator', implemented: true },
      { id: 'tdee-calculator', title: 'TDEE Calculator', description: 'Calculate Total Daily Energy Expenditure', path: '/tools/calculators/tdee-calculator', implemented: true },
    ],
  },
  {
    id: 'converters',
    title: 'Converters',
    description: 'Convert between different units and formats',
    icon: ArrowLeftRight,
    color: 'converterTool',
    gradient: 'converterTool-gradient',
    tools: [
      { id: 'length-converter', title: 'Length Converter', description: 'Convert between different units of length', path: '/tools/converters/length-converter', implemented: true },
      { id: 'unit-converter', title: 'Unit Converter', description: 'Convert between different measurement units', path: '/tools/converters/unit-converter', implemented: true },
      { id: 'color-converter', title: 'Color Converter', description: 'Convert between color formats (HEX, RGB, HSL)', path: '/tools/converters/color-converter', implemented: true },
    ],
  },
  {
    id: 'binary',
    title: 'Binary Tools',
    description: 'Work with binary data and encoding',
    icon: Binary,
    color: 'binaryTool',
    gradient: 'binaryTool-gradient',
    tools: [
      { id: 'base64-converter', title: 'Base64 Encoder/Decoder', description: 'Convert text to/from Base64 encoding', path: '/tools/binary/base64-converter', implemented: true },
      { id: 'ascii-to-binary', title: 'ASCII to Binary Converter', description: 'Convert ASCII text to binary and vice versa', path: '/tools/binary/AsciiToBinaryConverter', implemented: true },
      { id: 'Binary-To-Decimal', title: 'Binary to Decimal Converter', description: 'Convert binary numbers to decimal and vice versa', path: '/tools/binary/BinaryToDecimal', implemented: true },
      { id: 'Binary-To-Hex', title: 'Binary to Hex Converter', description: 'Convert binary numbers to hexadecimal and vice versa', path: '/tools/binary/BinaryToHex', implemented: true },
      { id: 'Binary-To-Octal', title: 'Binary to Octal Converter', description: 'Convert binary numbers to octal and vice versa', path: '/tools/binary/BinaryToOctal', implemented: true },
      { id: 'Binary-To-Text', title: 'Binary to Text Converter', description: 'Convert binary numbers to text and vice versa', path: '/tools/binary/BinaryToText', implemented: true },
      { id: 'Decimal-To-Binary', title: 'Decimal to Binary Converter', description: 'Convert decimal numbers to binary and vice versa', path: '/tools/binary/DecimalToBinary', implemented: true },
      { id: 'Decimal-To-Hex', title: 'Decimal to Hex Converter', description: 'Convert decimal numbers to hexadecimal and vice versa', path: '/tools/binary/DecimalToHex', implemented: true },
      { id: 'Decimal-To-Octal', title: 'Decimal to Octal Converter', description: 'Convert decimal numbers to octal and vice versa', path: '/tools/binary/DecimalToOctal', implemented: true },
      { id: 'Decimal-To-Text', title: 'Decimal to Text Converter', description: 'Convert decimal numbers to text and vice versa', path: '/tools/binary/DecimalToText', implemented: true },
      { id: 'Hex-Converter', title: 'Hex Converter', description: 'Convert hexadecimal numbers to various formats', path: '/tools/binary/hex-converter', implemented: true },
      { id: 'Hex-To-Binary', title: 'Hex to Binary Converter', description: 'Convert hexadecimal numbers to binary and vice versa', path: '/tools/binary/HexToBinary', implemented: true },
      { id: 'Hex-To-Decimal', title: 'Hex to Decimal Converter', description: 'Convert hexadecimal numbers to decimal and vice versa', path: '/tools/binary/HexToDecimal', implemented: true },
      { id: 'Hex-To-Octal', title: 'Hex to Octal Converter', description: 'Convert hexadecimal numbers to octal and vice versa', path: '/tools/binary/HexToOctal', implemented: true },
      { id: 'Hex-To-Text', title: 'Hex to Text Converter', description: 'Convert hexadecimal numbers to text and vice versa', path: '/tools/binary/HexToText', implemented: true },
      { id: 'Octal-To-Binary', title: 'Octal to Binary Converter', description: 'Convert octal numbers to binary and vice versa', path: '/tools/binary/OctalToBinary', implemented: true },
      { id: 'Octal-To-Decimal', title: 'Octal to Decimal Converter', description: 'Convert octal numbers to decimal and vice versa', path: '/tools/binary/OctalToDecimal', implemented: true },
      { id: 'Octal-To-Hex', title: 'Octal to Hex Converter', description: 'Convert octal numbers to hexadecimal and vice versa', path: '/tools/binary/OctalToHex', implemented: true },
      { id: 'Octal-To-Text', title: 'Octal to Text Converter', description: 'Convert octal numbers to text and vice versa', path: '/tools/binary/OctalToText', implemented: true },
      { id: 'Text-To-Binary', title: 'Text to Binary Converter', description: 'Convert text to binary and vice versa', path: '/tools/binary/TextToBinary', implemented: true },
      { id: 'Text-To-Decimal', title: 'Text to Decimal Converter', description: 'Convert text to decimal and vice versa', path: '/tools/binary/TextToDecimal', implemented: true },
      { id: 'Text-To-Hex', title: 'Text to Hex Converter', description: 'Convert text to hexadecimal and vice versa', path: '/tools/binary/TextToHex', implemented: true },
      { id: 'Text-To-Octal', title: 'Text to Octal Converter', description: 'Convert text to octal and vice versa', path: '/tools/binary/TextToOctal', implemented: true },
    ],
  },
  {
    id: 'website',
    title: 'Website Tools',
    description: 'Tools for web development and management',
    icon: Globe,
    color: 'websiteTool',
    gradient: 'websiteTool-gradient',
    tools: [
      { id: 'html-minifier', title: 'HTML Minifier', description: 'Minify HTML code to reduce file size', path: '/tools/website/html-minifier', implemented: true },
      { id: 'css-minifier', title: 'CSS Minifier', description: 'Minify CSS code to reduce file size', path: '/tools/website/css-minifier', implemented: true },
      { id: 'html-decode', title: 'HTML Decode', description: 'Decode HTML entities to plain text', path: '/tools/website/html-decode', implemented: true },
      { id: 'url-encoder', title: 'URL Encoder', description: 'Encode URLs to make them safe for transmission', path: '/tools/website/URLEncode', implemented: true },
      { id: 'url-decoder', title: 'URL Decoder', description: 'Decode URL-encoded strings back to normal text', path: '/tools/website/URLDecode', implemented: true },
      { id: 'javascript-minifier', title: 'JavaScript Minifier', description: 'Minify JavaScript code to reduce file size', path: '/tools/website/JavascriptMinifier', implemented: true },
      { id: 'javascript-beautifier', title: 'JavaScript Beautifier', description: 'Beautify and format JavaScript code for readability', path: '/tools/website/JavascriptBeautifier', implemented: true },
      { id: 'JavaScript-Obfuscator', title: 'JavaScript Obfuscator', description: 'Obfuscate JavaScript code to protect it from reverse engineering', path: '/tools/website/JavascriptObfuscator', implemented: true },
      { id: 'JavaScript-Deobfuscator', title: 'JavaScript Deobfuscator', description: 'Deobfuscate JavaScript code to make it readable', path: '/tools/website/JavascriptDeObfuscator', implemented: true },
      { id: 'QR Code Generator', title: 'QR Code Generator', description: 'Generate QR codes from text or URLs', path: '/tools/website/QRCodeGenerator', implemented: true },
      { id: 'QR Code Decoder', title: 'QR Code Decoder', description: 'Decode QR codes from images', path: '/tools/website/QRCodeDecoder', implemented: true },
    ],
  },
  {
    id: 'dev',
    title: 'Dev Tools',
    description: 'Tools for developers and programmers',
    icon: Code,
    color: 'devTool',
    gradient: 'devTool-gradient',
    tools: [
      { id: 'json-formatter', title: 'JSON Formatter', description: 'Format, validate and beautify JSON data', path: '/tools/dev/json-formatter', implemented: true },
      { id: 'regex-tester', title: 'Regex Tester', description: 'Test regular expressions with visual feedback', path: '/tools/dev/regex-tester', implemented: true },
    ],
  },
  {
    id: 'code',
    title: 'Code Tools',
    description: 'Format, validate and convert code and data',
    icon: Code,
    color: 'codeTool',
    gradient: 'codeTool-gradient',
    tools: [
      { id: 'json-formatter', title: 'JSON Formatter', description: 'Format, validate and beautify JSON data', path: '/tools/dev/json-formatter', implemented: true },
      { id: 'base64-converter', title: 'Base64 Encode/Decode', description: 'Encode and decode text to and from Base64', path: '/tools/code/base64-converter', implemented: true },
      { id: 'jwt-decoder', title: 'JWT Decoder', description: 'Decode and inspect JWT tokens', path: '/tools/code/jwt-decoder', implemented: true },
    ],
  },
  {
    id: 'misc',
    title: 'Miscellaneous',
    description: 'Other useful tools and utilities',
    icon: Package,
    color: 'miscTool',
    gradient: 'miscTool-gradient',
    tools: [
      { id: 'password-generator', title: 'Password Generator', description: 'Generate secure random passwords', path: '/tools/misc/password-generator', implemented: true },
      { id: 'uuid-generator', title: 'UUID Generator', description: 'Generate random UUIDs (v4)', path: '/tools/misc/uuid-generator', implemented: true },
      { id: 'Facebook Finder', title: 'Facebook IDFinder', description: 'Find Facebook profiles by name or email', path: '/tools/misc/FacebookidFinder', implemented: true },
      { id: 'Utm Builder', title: 'UTM Builder', description: 'Create UTM parameters for tracking links', path: '/tools/misc/UTMBuilder', implemented: true },
    ],
  },
];
